Preset refactor
ApocalyVec/RenaLabApp pull request #70
Opened 2023-04-23 06:02 UTC by ApocalyVec

2023-05-05 05:16 UTC, HaowenWeiJohn commented on rena/ui/StreamOptionsWindow.py
get_nomimal_sampling_rate -> get_nominal_sampling_rate

2023-05-05 05:19 UTC, HaowenWeiJohn commented on rena/ui/StreamOptionsWindow.py
The switching between other plotting profile  and Image will accumulate the Invalid Image Format Print  statement exponentially.
![image](https://user-images.githubusercontent.com/59973823/236382396-566cd4bd-e3b8-4e2a-a430-c4f959c4aa15.png)

2023-05-05 05:28 UTC, HaowenWeiJohn requested changes

2023-05-05 05:28 UTC, HaowenWeiJohn commented on rena/ui/StreamOptionsWindow.py
The self.dataDisplayDurationLineEdit has no effect to the Spectrogram plot
The spectrogram should automatically resize to the proper size based on the value in dataDisplayDurationLineEdit after the user switch to it.

2023-05-09 18:52 UTC, ApocalyVec commented on rena/ui/StreamOptionsWindow.py
Both issue fixed per [commit]https://github.com/ApocalyVec/RenaLabApp/pull/70/commits/6687b465a01f40e9221a2bb045a42383e2522370)

2023-05-09 18:54 UTC, ApocalyVec commented on rena/ui/StreamOptionsWindow.py
typo fixed per 652831e4a4ce9832e2de4d24929c452f25f0aaa8

2023-05-12 19:15 UTC, HaowenWeiJohn approved these changes
Presets Refactor Reviewed

2023-05-12 19:20 UTC, merged